export const ASSET_HEADERS: Record<number, string[]> = {
  1: [
    'Asset Name',
    'Ticker',
    'Dividend Yield',
    'Total Quantity',
    'Average Purchase Price',
    'Total Invested',
    'Current Value',
    'Unrealized Gain/Loss',
    'Exchange',
    'Created At',
    'Updated At',
  ],
  2: [
    'Asset Name',
    'Coupon Rate',
    'Maturity Date',
    'Face Value',
    'Total Quantity',
    'Total Invested',
    'Current Value',
    'Unrealized Gain/Loss',
    'Exchange',
    'Interest Accrued',
    'Created At',
    'Updated At',
  ],
  3: [
    'Asset Name',
    'Ticker',
    'Dividend Yield',
    'Accumulation',
    'Total Quantity',
    'Average Purchase Price',
    'Total Invested',
    'Current Value',
    'Unrealized Gain/Loss',
    'Exchange',
    'Created At',
    'Updated At',
  ],
  4: [
    'Asset Name',
    'Ticker',
    'Total Quantity',
    'Average Purchase Price',
    'Total Invested',
    'Current Value',
    'Unrealized Gain/Loss',
    'Exchange',
    'Created At',
    'Updated At',
  ],
};
