export enum ExpenseCategoryNames {
  Children = 'Children',
  Clothing = 'Clothing',
  EatingOut = 'EatingOut',
  Education = 'Education',
  Electronics = 'Electronics',
  Entertainment = 'Entertainment',
  Gifts = 'Gifts',
  Groceries = 'Groceries',
  Health = 'Health',
  Hobby = 'Hobby',
  Hygiene = 'Hygiene',
  Insurance = 'Insurance',
  Investments = 'Investments',
  Obligations = 'Obligations',
  Other = 'Other',
  Other2 = 'Rest of the categories',
  Pets = 'Pets',
  Rent = 'Rent',
  Savings = 'Savings',
  Sport = 'Sport',
  Subscriptions = 'Subscriptions',
  Taxes = 'Taxes',
  Transport = 'Transport',
  Travel = 'Travel',
  Utility = 'Utility',
}

export enum IncomeCategoryNames {
  Bonus = 'Bonus',
  Gifts = 'Gifts',
  InvestmentsIncome = 'InvestmentsIncome',
  Salary = 'Salary',
  SideGig = 'SideGig',
}
